// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamerpilotPlatform.Data;

namespace gamerpilotPlatform.Migrations
{
    [DbContext(typeof(GamerpilotVodContext))]
    [Migration("20180831195222_addedIntro")]
    partial class addedIntro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("gamerpilotPlatform.Model.Course", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseLength");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Language");

                    b.Property<string>("Level");

                    b.Property<string>("LifeSkill");

                    b.Property<string>("Name");

                    b.Property<string>("UrlName");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.CourseIntroduction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("CourseIntroductions");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.Instructor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.LearningGoal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseIntroductionId");

                    b.Property<string>("Goal");

                    b.HasKey("Id");

                    b.HasIndex("CourseIntroductionId");

                    b.ToTable("LearningGoals");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseId");

                    b.Property<string>("CourseIntroductionId");

                    b.Property<string>("InstructorId");

                    b.Property<int>("LectureType");

                    b.Property<int>("Order");

                    b.Property<int>("Section");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseIntroductionId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.Instructor", b =>
                {
                    b.HasOne("gamerpilotPlatform.Model.Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.LearningGoal", b =>
                {
                    b.HasOne("gamerpilotPlatform.Model.CourseIntroduction")
                        .WithMany("LearningGoals")
                        .HasForeignKey("CourseIntroductionId");
                });

            modelBuilder.Entity("gamerpilotPlatform.Model.Lecture", b =>
                {
                    b.HasOne("gamerpilotPlatform.Model.Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId");

                    b.HasOne("gamerpilotPlatform.Model.CourseIntroduction", "CourseIntroduction")
                        .WithMany()
                        .HasForeignKey("CourseIntroductionId");

                    b.HasOne("gamerpilotPlatform.Model.Instructor", "Instructor")
                        .WithMany("Lectures")
                        .HasForeignKey("InstructorId");
                });
#pragma warning restore 612, 618
        }
    }
}
